name: Build, Tests and Examples

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run Smoke test
      run: cargo run -- demo/ci-smoke-test.json
    - name: Run current work
      run: cargo run --release -- -p demo/demo.json
    - name: Run examples
      run: for f in demo/*.json; do cargo run --release -- --width 60 --height 40 $f; done

